# Generated by Django 4.2.2 on 2023-06-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
