# Generated by Django 4.2.2 on 2023-06-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
