# Generated by Django 4.2.2 on 2023-07-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0002_alter_trainingsession_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='attendees',
            new_name='players',
        ),
    ]
