# Generated by Django 4.2.2 on 2023-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=200)),
                ('school_attended', models.CharField(max_length=200)),
                ('player_position', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_condition', models.BooleanField(default=False)),
                ('parent_full_name', models.CharField(max_length=150)),
                ('parent_phone_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
