# Generated by Django 4.2.2 on 2023-07-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0006_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_category', to='altar.categories'),
        ),
    ]
