# Generated by Django 4.2.2 on 2023-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0008_game_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='medical_condition_details',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
