# Generated by Django 4.2.2 on 2023-07-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0009_player_medical_condition_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='medical_condition_details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
