# Generated by Django 4.2.2 on 2023-07-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0010_alter_player_medical_condition_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='medical_condition',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
