# Generated by Django 4.2.2 on 2023-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altar', '0011_alter_player_medical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='medical_condition_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
